spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meal_planet
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver


server:
  port: 9085

  servlet:
    context-path: /mealplanet

